manifest:
  remotes:
    - name: akadimia
      url-base: https://github.com/liangyongqin

  projects:
    - name: akadimia-sdk
      remote: akadimia
      repo-path: akadimia-sdk
      revision: main
      path: akadimia-sdk
      import: true
      
  self:
    path: .
